### ISSUE TITLE
KCMinit closed unexpectedly

### ISSUE THREAD

**Issue by bluecoon** [KaOSx/calamares#66]
I cannot install KAOS on my system. I tried running it from CD and USB, both the current version and the august 2015 version. On all occasions the live CD loads and next the screen freezes. The august 2015 version shows an error dialog: "KCMinit closed unexpectedly". At that point I can only reboot my computer... No problems in a VirtualBox.

**Comment by demmm** [comment]
Since you opened an issue for the installer, not clear if you have issues on rebooting after the install or if you can't boot the live mode.
If the latter, you need to open an issue in https://github.com/KaOSx/live-uefi/issues
Before opening an issue there, did you follow the instructions how to create supported Live Media?
See right column on many pages, example http://kaosx.us/download/
To create a more useful report see:
http://kaosx.us/asking-and-reporting-the-smart-way/

**Comment by bluecoon** [comment]
On Wednesday, August 12, 2015 09:24:12 AM demmm wrote:
>  not clear if you have issues on rebooting after the install or
>  if you can't boot the live mode.

Strictly speaking I CAN boot the live mode - but only up to the moment where 
the 'welcome' window (with the installer) appears. At that moment I have a 
complete KDE desktop but can't do anything with it - mouse and keyboard are 
ignored. Consequently I can't even start the installation.

regards,

JS

**Comment by demmm** [comment]
Not a Calamares issue, install was never tried.  No further response from submitter for needed logs and correct Live media creation, closing.
